services:
  nginx:
    container_name: nginx
    image: nginx
    user: root
    volumes:
      - ./html:/var/www/html
      - ./templates:/etc/nginx/templates
      - /var/lib/docker/volumes/files/_data:/opt/files
    network_mode: host
    env_file: .env

volumes:
  proxy:
