services:
  nginx:
    container_name: nginx
    image: nginx:latest
    entrypoint: ["/docker-entrypoint.sh"]
    user: root
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./html:/var/www/html
      - ./templates:/etc/nginx/templates
      - ./conf.d:/etc/nginx/conf.d
      - ./files:/var/www/files
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    env_file: .env

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    profiles: ["manual"]

volumes:
  nginx:
